### ISSUE TITLE
Something is broken with event-push plugin

### ISSUE THREAD

**Issue by fuxiaoalex** [smaldini/grails-events-push#11]
It's working well yesterday night, but the plugin seems broken today.

And I don't change anything of my code.

I get message like:

2012-08-03 13:01:51,811 [Atmosphere-AsyncWrite-0] WARN  gateway.GatewayProxyFactoryBean$MethodInvocationGateway  - failure occurred in gateway sendAndReceive
org.springframework.integration.MessageDeliveryException: failed to send Message to channel 'gorm://afterInsert'
    at org.grails.plugin.platform.events.publisher.SpringIntegrationEventsPublisher.event(SpringIntegrationEventsPublisher.java:63)
    at org.grails.plugin.platform.events.publisher.GormBridgePublisher.onApplicationEvent(GormBridgePublisher.java:59)
    at ChatAtmosphereHandler$_onStateChange_closure1.doCall(ChatAtmosphereHandler.groovy:68)
    at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:573)
    at ChatAtmosphereHandler.onStateChange(ChatAtmosphereHandler.groovy:66)
    at org.atmosphere.cpr.DefaultBroadcaster.broadcast(DefaultBroadcaster.java:845)
    at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:760)
    at org.atmosphere.cpr.DefaultBroadcaster$3.run(DefaultBroadcaster.java:793)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
Caused by: org.springframework.amqp.support.converter.MessageConversionException: failed to convert to serialized Message content
    ... 14 more
Caused by: java.lang.IllegalArgumentException: Could not serialize object of type: class org.springframework.integration.message.GenericMessage
    ... 14 more
Caused by: java.io.NotSerializableException: com.test.ChatLog
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1164)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1518)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1483)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1400)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1158)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:330)
    at java.util.HashMap.writeObject(HashMap.java:1001)
    at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:940)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1469)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1400)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1158)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1518)
    at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:422)
    at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:940)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1469)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1400)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1158)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1518)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1483)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1400)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1158)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:330)
    ... 14 more

The error came from a place where I did "SomeDomain.save()"

But I registered "gorm:// afterInsert" listen for another domain not that one where the error occurs...

**Comment by fuxiaoalex** [comment]
Or maybe is the problem of "Event-si" plugin

**Comment by smaldini** [comment]
The problem comes from platform-core update in fact. It's not a bug, it's a feature ! MessageDeliveryException and others exceptions are now properly raised to caller (before they could have been hidden).

Did you try to add Serializable to your ChatLog.

**Comment by fuxiaoalex** [comment]
Yes, you're right....

Thank you for reply!

**Comment by eeble** [comment]
What was the resolution to this issue? I am seeing the same issue with 1.0M7 where I have to add a 3rd argument of an empty closure in order for the server initiated event to actually be received by the browser.
