### ISSUE TITLE
something fails deploying in AppFog

### ISSUE THREAD

**Issue by chiquitinxx** [smaldini/grails-events-push#26]
Hello!

In my computer all works fine, but when deploying on AppFog i get this error. Dunno if an AppFog issue, or grails configuration problem, or grails-events-push,... Thanks!

2013-01-02 00:08:41,819 [main] ERROR cpr.AtmosphereFramework  - Failed to initialize Atmosphere Framework
java.lang.NoClassDefFoundError: org/grails/plugin/platform/events/push/EventsPushHandler$1
    at org.grails.plugin.platform.events.push.EventsPushHandler.init(EventsPushHandler.java:108)
    at org.atmosphere.util.AtmosphereFilterChain.init(AtmosphereFilterChain.java:125)
...
Caused by: java.lang.ClassNotFoundException: org.grails.plugin.platform.events.push.EventsPushHandler$1
    ... 9 more
java.io.FileNotFoundException: /var/vcap.local/dea/apps/grooscript-0-0613fa7183e2ca45eae953304f9817cd/tomcat/../tomcat.state (Too many open files)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at java.io.PrintWriter.<init>(Unknown Source)
    at com.vmware.appcloud.tomcat.AppCloudLifecycleListener.handleNotification(A

**Comment by chiquitinxx** [comment]
there is a limit of 256 files open in appfog, maybe is that the problem. So i close.

**Comment by smaldini** [comment]
Right I get the same problem too, investigating.

**Comment by smaldini** [comment]
seems to be linked to multi factors:
- Resources plugin: Peak load of FD on start and 1st request
- Grails dependencies (a JAR = an open FD)
- Others stuff.
- 256 FD is damn low anyway
  Closing that one as its not related unfortunately
