### ISSUE TITLE
NullPointerException when starting a project using event-push on linux with tomcat-7.0.39

### ISSUE THREAD

**Issue by jpboudreault** [smaldini/grails-events-push#40]
Hi,
I love the way this project integrates push notifications with grails. It works in my dev machine with grails run-app (windows) perfectly. Unfortunately, when deploying the war on a tomcat-7.0.39 I get the following error :

cpr.AtmosphereFramework Atmosphere is using org.atmosphere.cpr.DefaultAnnotationProcessor for processing annotation
cpr.AnnotationHandler Found Annotation in class org.grails.plugin.platform.events.push.EventsPushHandler being scanned: interface org.atmosphere.config.service.MeteorService
cpr.AnnotationHandler 
**java.lang.NullPointerException**
    at org.atmosphere.cpr.AtmosphereFramework.setDefaultBroadcasterClassName(AtmosphereFramework.java:1634)
    at org.atmosphere.cpr.AnnotationHandler.handleAnnotation(AnnotationHandler.java:136)
    at org.atmosphere.cpr.DefaultAnnotationProcessor$ServletContainerInitializerAnnotationProcessor.scan(DefaultAnnotationProcessor.java:128)
    at org.atmosphere.cpr.DefaultAnnotationProcessor.scan(DefaultAnnotationProcessor.java:81)
    at org.atmosphere.cpr.AtmosphereFramework.autoConfigureService(AtmosphereFramework.java:2002)
    at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:568)
    at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:507)
    at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:74)
    at org.atmosphere.cpr.MeteorServlet.init(MeteorServlet.java:122)
    at org.grails.plugin.platform.events.push.GrailsMeteorServlet.init(GrailsMeteorServlet.java:37)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:636)

Afterwards, the events are never pushed to the client. Do I need to setup something special in tomcat server.xml besides changing the connectors to NIO?

Thanks!

**Comment by jpboudreault** [comment]
I am under the impression that the problem is atmosphere being in the same war as event push. While debugging on my dev environment the BytecodeBasedAnnotationProcessor is used by the DefaultAnnotationProcessor while the stracktrace gotten in a production tomcat shows that the ServletContainerInitializerAnnotationProcessor is used. The ServletContainerInitializerAnnotationProcessor discovers the EventsPushHandler and throws the error.

**Comment by jpboudreault** [comment]
The error is still present but it is not blocking the event push. My Events.groovy file was located under conf/spring and  this was causing events to be ignored when the project was running from a war.

**Comment by jfarcand** [comment]
This is fixed with the integration of Atmosphere 2.0.1
